// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: authz.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthZService_CheckAccess_FullMethodName      = "/api.AuthZService/CheckAccess"
	AuthZService_BatchCheckAccess_FullMethodName = "/api.AuthZService/BatchCheckAccess"
)

// AuthZServiceClient is the client API for AuthZService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthZServiceClient interface {
	CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error)
	BatchCheckAccess(ctx context.Context, in *BatchCheckAccessRequest, opts ...grpc.CallOption) (*BatchCheckAccessResponse, error)
}

type authZServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthZServiceClient(cc grpc.ClientConnInterface) AuthZServiceClient {
	return &authZServiceClient{cc}
}

func (c *authZServiceClient) CheckAccess(ctx context.Context, in *CheckAccessRequest, opts ...grpc.CallOption) (*CheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckAccessResponse)
	err := c.cc.Invoke(ctx, AuthZService_CheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authZServiceClient) BatchCheckAccess(ctx context.Context, in *BatchCheckAccessRequest, opts ...grpc.CallOption) (*BatchCheckAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCheckAccessResponse)
	err := c.cc.Invoke(ctx, AuthZService_BatchCheckAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthZServiceServer is the server API for AuthZService service.
// All implementations must embed UnimplementedAuthZServiceServer
// for forward compatibility.
type AuthZServiceServer interface {
	CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error)
	BatchCheckAccess(context.Context, *BatchCheckAccessRequest) (*BatchCheckAccessResponse, error)
	mustEmbedUnimplementedAuthZServiceServer()
}

// UnimplementedAuthZServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthZServiceServer struct{}

func (UnimplementedAuthZServiceServer) CheckAccess(context.Context, *CheckAccessRequest) (*CheckAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAccess not implemented")
}
func (UnimplementedAuthZServiceServer) BatchCheckAccess(context.Context, *BatchCheckAccessRequest) (*BatchCheckAccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCheckAccess not implemented")
}
func (UnimplementedAuthZServiceServer) mustEmbedUnimplementedAuthZServiceServer() {}
func (UnimplementedAuthZServiceServer) testEmbeddedByValue()                      {}

// UnsafeAuthZServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthZServiceServer will
// result in compilation errors.
type UnsafeAuthZServiceServer interface {
	mustEmbedUnimplementedAuthZServiceServer()
}

func RegisterAuthZServiceServer(s grpc.ServiceRegistrar, srv AuthZServiceServer) {
	// If the following call pancis, it indicates UnimplementedAuthZServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthZService_ServiceDesc, srv)
}

func _AuthZService_CheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthZServiceServer).CheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthZService_CheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthZServiceServer).CheckAccess(ctx, req.(*CheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthZService_BatchCheckAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCheckAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthZServiceServer).BatchCheckAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthZService_BatchCheckAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthZServiceServer).BatchCheckAccess(ctx, req.(*BatchCheckAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthZService_ServiceDesc is the grpc.ServiceDesc for AuthZService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthZService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.AuthZService",
	HandlerType: (*AuthZServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckAccess",
			Handler:    _AuthZService_CheckAccess_Handler,
		},
		{
			MethodName: "BatchCheckAccess",
			Handler:    _AuthZService_BatchCheckAccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authz.proto",
}
