// Code generated by protoc-gen-permissions. DO NOT EDIT.
package pb

import "github.com/ashish19912009/zrms/services/account/pkg/permissions"

func init() {
	permissions.Register("/account.AccountService/CreateFranchise", "franchise", "create")
	permissions.Register("/account.AccountService/UpdateFranchise", "franchise", "update")
	permissions.Register("/account.AccountService/UpdateFranchiseStatus", "franchiseStatus", "update")
	permissions.Register("/account.AccountService/DeleteFranchise", "franchise", "delete")
	permissions.Register("/account.AccountService/GetAllFranchises", "franchise", "viewAll")
	permissions.Register("/account.AccountService/GetFranchiseByID", "franchise", "view")
	permissions.Register("/account.AccountService/CreateFranchiseDocument", "franchiseDocument", "create")
	permissions.Register("/account.AccountService/GetFranchiseDocumentByID", "franchiseDocument", "view")
	permissions.Register("/account.AccountService/UpdateFranchiseDocumentByID", "franchiseDocument", "update")
	permissions.Register("/account.AccountService/DeleteFranchiseDocumentByID", "franchiseDocument", "delete")
	permissions.Register("/account.AccountService/CreateFranchiseAddress", "franchiseAddress", "create")
	permissions.Register("/account.AccountService/GetFranchiseAddressByID", "franchiseAddress", "view")
	permissions.Register("/account.AccountService/UpdateFranchiseAddressByID", "franchiseAddress", "update")
	permissions.Register("/account.AccountService/CreateFranchiseOwner", "franchiseOwner", "create")
	permissions.Register("/account.AccountService/UpdateFranchiseOwnerByID", "franchiseOwner", "update")
	permissions.Register("/account.AccountService/GetFranchiseOwnerByID", "franchiseOwner", "view")
	permissions.Register("/account.AccountService/CreateFranchiseAccount", "franchiseAccount", "create")
	permissions.Register("/account.AccountService/GetFranchiseAccountByID", "franchiseAccount", "view")
	permissions.Register("/account.AccountService/GetFranchiseAccounts", "franchiseAccount", "viewAll")
	permissions.Register("/account.AccountService/UpdateFranchiseAccountByID", "franchiseAccount", "update")
	permissions.Register("/account.AccountService/DeleteFranchiseAccountByID", "franchiseAccount", "delete")
}
