// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/account.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountService_CreateFranchise_FullMethodName              = "/account.AccountService/CreateFranchise"
	AccountService_UpdateFranchise_FullMethodName              = "/account.AccountService/UpdateFranchise"
	AccountService_UpdateFranchiseStatus_FullMethodName        = "/account.AccountService/UpdateFranchiseStatus"
	AccountService_DeleteFranchise_FullMethodName              = "/account.AccountService/DeleteFranchise"
	AccountService_GetAllFranchises_FullMethodName             = "/account.AccountService/GetAllFranchises"
	AccountService_GetFranchiseByID_FullMethodName             = "/account.AccountService/GetFranchiseByID"
	AccountService_GetFranchiseByBusinessName_FullMethodName   = "/account.AccountService/GetFranchiseByBusinessName"
	AccountService_CreateFranchiseDocument_FullMethodName      = "/account.AccountService/CreateFranchiseDocument"
	AccountService_GetFranchiseDocumentByID_FullMethodName     = "/account.AccountService/GetFranchiseDocumentByID"
	AccountService_UpdateFranchiseDocumentByID_FullMethodName  = "/account.AccountService/UpdateFranchiseDocumentByID"
	AccountService_DeleteFranchiseDocumentByID_FullMethodName  = "/account.AccountService/DeleteFranchiseDocumentByID"
	AccountService_CreateFranchiseAddress_FullMethodName       = "/account.AccountService/CreateFranchiseAddress"
	AccountService_GetFranchiseAddressByID_FullMethodName      = "/account.AccountService/GetFranchiseAddressByID"
	AccountService_UpdateFranchiseAddressByID_FullMethodName   = "/account.AccountService/UpdateFranchiseAddressByID"
	AccountService_CreateNewOwner_FullMethodName               = "/account.AccountService/CreateNewOwner"
	AccountService_UpdateFranchiseOwnerByID_FullMethodName     = "/account.AccountService/UpdateFranchiseOwnerByID"
	AccountService_GetFranchiseOwnerByID_FullMethodName        = "/account.AccountService/GetFranchiseOwnerByID"
	AccountService_CheckIfOwnerExistsByAadharID_FullMethodName = "/account.AccountService/CheckIfOwnerExistsByAadharID"
	AccountService_CreateFranchiseAccount_FullMethodName       = "/account.AccountService/CreateFranchiseAccount"
	AccountService_GetFranchiseAccountByID_FullMethodName      = "/account.AccountService/GetFranchiseAccountByID"
	AccountService_GetFranchiseAccounts_FullMethodName         = "/account.AccountService/GetFranchiseAccounts"
	AccountService_UpdateFranchiseAccountByID_FullMethodName   = "/account.AccountService/UpdateFranchiseAccountByID"
	AccountService_DeleteFranchiseAccountByID_FullMethodName   = "/account.AccountService/DeleteFranchiseAccountByID"
	AccountService_CreateFranchiseRole_FullMethodName          = "/account.AccountService/CreateFranchiseRole"
	AccountService_UpdateFranchiseRole_FullMethodName          = "/account.AccountService/UpdateFranchiseRole"
	AccountService_GetAllFranchiseRoles_FullMethodName         = "/account.AccountService/GetAllFranchiseRoles"
	AccountService_AddPermissionsToRole_FullMethodName         = "/account.AccountService/AddPermissionsToRole"
	AccountService_UpdatePermissionsToRole_FullMethodName      = "/account.AccountService/UpdatePermissionsToRole"
	AccountService_GetAllPermissionToRole_FullMethodName       = "/account.AccountService/GetAllPermissionToRole"
)

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountServiceClient interface {
	// Franchise RPC's
	CreateFranchise(ctx context.Context, in *AddFranchiseRequest, opts ...grpc.CallOption) (*AddResponse, error)
	UpdateFranchise(ctx context.Context, in *UpdateFranchiseRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	UpdateFranchiseStatus(ctx context.Context, in *UpdateFranchiseStatusRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteFranchise(ctx context.Context, in *DeleteFranchiseRequest, opts ...grpc.CallOption) (*DeletedResponse, error)
	GetAllFranchises(ctx context.Context, in *GetFranchisesRequest, opts ...grpc.CallOption) (*GetFranchisesResponse, error)
	GetFranchiseByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetFranchiseByIDResponse, error)
	GetFranchiseByBusinessName(ctx context.Context, in *GetFranchiseByName, opts ...grpc.CallOption) (*GetFranchiseByIDResponse, error)
	// Franchise Document RPC's
	CreateFranchiseDocument(ctx context.Context, in *AddFranchiseDocumentRequest, opts ...grpc.CallOption) (*AddResponse, error)
	GetFranchiseDocumentByID(ctx context.Context, in *GetFranchiseDocumentRequest, opts ...grpc.CallOption) (*GetFranchiseDocumentResponse, error)
	UpdateFranchiseDocumentByID(ctx context.Context, in *UpdateFranchiseDocumentRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteFranchiseDocumentByID(ctx context.Context, in *DeleteFranchiseDocumentRequest, opts ...grpc.CallOption) (*DeletedResponse, error)
	// Franchise Address RPC's
	CreateFranchiseAddress(ctx context.Context, in *AddFranchiseAddressRequest, opts ...grpc.CallOption) (*AddResponse, error)
	GetFranchiseAddressByID(ctx context.Context, in *GetFranchiseAddressRequest, opts ...grpc.CallOption) (*GetFranchiseAddressResponse, error)
	UpdateFranchiseAddressByID(ctx context.Context, in *UpdateFranchiseAddressRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// Franchise Owner RPC's
	CreateNewOwner(ctx context.Context, in *AddFranchiseOwnerRequest, opts ...grpc.CallOption) (*AddResponse, error)
	UpdateFranchiseOwnerByID(ctx context.Context, in *UpdateFranchiseOwnerRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetFranchiseOwnerByID(ctx context.Context, in *GetFranchiseOwnerRequest, opts ...grpc.CallOption) (*GetFranchiseOwnerResponse, error)
	CheckIfOwnerExistsByAadharID(ctx context.Context, in *AadharNoRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// Franchise Accounts RPC's
	CreateFranchiseAccount(ctx context.Context, in *AddFranchiseAccountRequest, opts ...grpc.CallOption) (*AddResponse, error)
	GetFranchiseAccountByID(ctx context.Context, in *GetFranchiseAccountByIDRequest, opts ...grpc.CallOption) (*GetFranchiseAccountByIDResponse, error)
	GetFranchiseAccounts(ctx context.Context, in *GetFranchiseAccountsRequest, opts ...grpc.CallOption) (*GetFranchiseAccountsResponse, error)
	UpdateFranchiseAccountByID(ctx context.Context, in *UpdateFranchiseAccountRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	DeleteFranchiseAccountByID(ctx context.Context, in *DeleteFranchiseAccountRequest, opts ...grpc.CallOption) (*DeletedResponse, error)
	// Franchise Role RPC's
	CreateFranchiseRole(ctx context.Context, in *AddFranchiseRoleRequest, opts ...grpc.CallOption) (*AddResponse, error)
	UpdateFranchiseRole(ctx context.Context, in *UpdateFranchiseRoleRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	GetAllFranchiseRoles(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*FranchiseRoleResponse, error)
	// Franchise Role Permission RPC's
	AddPermissionsToRole(ctx context.Context, in *AddRolePermission, opts ...grpc.CallOption) (*AddRolePermission, error)
	UpdatePermissionsToRole(ctx context.Context, in *AddRolePermission, opts ...grpc.CallOption) (*AddRolePermission, error)
	GetAllPermissionToRole(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetAllRolePermissionDetails, error)
}

type accountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountServiceClient(cc grpc.ClientConnInterface) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateFranchise(ctx context.Context, in *AddFranchiseRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateFranchise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateFranchise(ctx context.Context, in *UpdateFranchiseRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateFranchise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateFranchiseStatus(ctx context.Context, in *UpdateFranchiseStatusRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateFranchiseStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteFranchise(ctx context.Context, in *DeleteFranchiseRequest, opts ...grpc.CallOption) (*DeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletedResponse)
	err := c.cc.Invoke(ctx, AccountService_DeleteFranchise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAllFranchises(ctx context.Context, in *GetFranchisesRequest, opts ...grpc.CallOption) (*GetFranchisesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchisesResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAllFranchises_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetFranchiseByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetFranchiseByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchiseByIDResponse)
	err := c.cc.Invoke(ctx, AccountService_GetFranchiseByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetFranchiseByBusinessName(ctx context.Context, in *GetFranchiseByName, opts ...grpc.CallOption) (*GetFranchiseByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchiseByIDResponse)
	err := c.cc.Invoke(ctx, AccountService_GetFranchiseByBusinessName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateFranchiseDocument(ctx context.Context, in *AddFranchiseDocumentRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateFranchiseDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetFranchiseDocumentByID(ctx context.Context, in *GetFranchiseDocumentRequest, opts ...grpc.CallOption) (*GetFranchiseDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchiseDocumentResponse)
	err := c.cc.Invoke(ctx, AccountService_GetFranchiseDocumentByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateFranchiseDocumentByID(ctx context.Context, in *UpdateFranchiseDocumentRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateFranchiseDocumentByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteFranchiseDocumentByID(ctx context.Context, in *DeleteFranchiseDocumentRequest, opts ...grpc.CallOption) (*DeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletedResponse)
	err := c.cc.Invoke(ctx, AccountService_DeleteFranchiseDocumentByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateFranchiseAddress(ctx context.Context, in *AddFranchiseAddressRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateFranchiseAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetFranchiseAddressByID(ctx context.Context, in *GetFranchiseAddressRequest, opts ...grpc.CallOption) (*GetFranchiseAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchiseAddressResponse)
	err := c.cc.Invoke(ctx, AccountService_GetFranchiseAddressByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateFranchiseAddressByID(ctx context.Context, in *UpdateFranchiseAddressRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateFranchiseAddressByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateNewOwner(ctx context.Context, in *AddFranchiseOwnerRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateNewOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateFranchiseOwnerByID(ctx context.Context, in *UpdateFranchiseOwnerRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateFranchiseOwnerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetFranchiseOwnerByID(ctx context.Context, in *GetFranchiseOwnerRequest, opts ...grpc.CallOption) (*GetFranchiseOwnerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchiseOwnerResponse)
	err := c.cc.Invoke(ctx, AccountService_GetFranchiseOwnerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CheckIfOwnerExistsByAadharID(ctx context.Context, in *AadharNoRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, AccountService_CheckIfOwnerExistsByAadharID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateFranchiseAccount(ctx context.Context, in *AddFranchiseAccountRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateFranchiseAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetFranchiseAccountByID(ctx context.Context, in *GetFranchiseAccountByIDRequest, opts ...grpc.CallOption) (*GetFranchiseAccountByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchiseAccountByIDResponse)
	err := c.cc.Invoke(ctx, AccountService_GetFranchiseAccountByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetFranchiseAccounts(ctx context.Context, in *GetFranchiseAccountsRequest, opts ...grpc.CallOption) (*GetFranchiseAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFranchiseAccountsResponse)
	err := c.cc.Invoke(ctx, AccountService_GetFranchiseAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateFranchiseAccountByID(ctx context.Context, in *UpdateFranchiseAccountRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateFranchiseAccountByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteFranchiseAccountByID(ctx context.Context, in *DeleteFranchiseAccountRequest, opts ...grpc.CallOption) (*DeletedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletedResponse)
	err := c.cc.Invoke(ctx, AccountService_DeleteFranchiseAccountByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateFranchiseRole(ctx context.Context, in *AddFranchiseRoleRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, AccountService_CreateFranchiseRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateFranchiseRole(ctx context.Context, in *UpdateFranchiseRoleRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, AccountService_UpdateFranchiseRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAllFranchiseRoles(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*FranchiseRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FranchiseRoleResponse)
	err := c.cc.Invoke(ctx, AccountService_GetAllFranchiseRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) AddPermissionsToRole(ctx context.Context, in *AddRolePermission, opts ...grpc.CallOption) (*AddRolePermission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRolePermission)
	err := c.cc.Invoke(ctx, AccountService_AddPermissionsToRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdatePermissionsToRole(ctx context.Context, in *AddRolePermission, opts ...grpc.CallOption) (*AddRolePermission, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRolePermission)
	err := c.cc.Invoke(ctx, AccountService_UpdatePermissionsToRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAllPermissionToRole(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GetAllRolePermissionDetails, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllRolePermissionDetails)
	err := c.cc.Invoke(ctx, AccountService_GetAllPermissionToRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
// All implementations must embed UnimplementedAccountServiceServer
// for forward compatibility.
type AccountServiceServer interface {
	// Franchise RPC's
	CreateFranchise(context.Context, *AddFranchiseRequest) (*AddResponse, error)
	UpdateFranchise(context.Context, *UpdateFranchiseRequest) (*UpdateResponse, error)
	UpdateFranchiseStatus(context.Context, *UpdateFranchiseStatusRequest) (*UpdateResponse, error)
	DeleteFranchise(context.Context, *DeleteFranchiseRequest) (*DeletedResponse, error)
	GetAllFranchises(context.Context, *GetFranchisesRequest) (*GetFranchisesResponse, error)
	GetFranchiseByID(context.Context, *GetByIDRequest) (*GetFranchiseByIDResponse, error)
	GetFranchiseByBusinessName(context.Context, *GetFranchiseByName) (*GetFranchiseByIDResponse, error)
	// Franchise Document RPC's
	CreateFranchiseDocument(context.Context, *AddFranchiseDocumentRequest) (*AddResponse, error)
	GetFranchiseDocumentByID(context.Context, *GetFranchiseDocumentRequest) (*GetFranchiseDocumentResponse, error)
	UpdateFranchiseDocumentByID(context.Context, *UpdateFranchiseDocumentRequest) (*UpdateResponse, error)
	DeleteFranchiseDocumentByID(context.Context, *DeleteFranchiseDocumentRequest) (*DeletedResponse, error)
	// Franchise Address RPC's
	CreateFranchiseAddress(context.Context, *AddFranchiseAddressRequest) (*AddResponse, error)
	GetFranchiseAddressByID(context.Context, *GetFranchiseAddressRequest) (*GetFranchiseAddressResponse, error)
	UpdateFranchiseAddressByID(context.Context, *UpdateFranchiseAddressRequest) (*UpdateResponse, error)
	// Franchise Owner RPC's
	CreateNewOwner(context.Context, *AddFranchiseOwnerRequest) (*AddResponse, error)
	UpdateFranchiseOwnerByID(context.Context, *UpdateFranchiseOwnerRequest) (*UpdateResponse, error)
	GetFranchiseOwnerByID(context.Context, *GetFranchiseOwnerRequest) (*GetFranchiseOwnerResponse, error)
	CheckIfOwnerExistsByAadharID(context.Context, *AadharNoRequest) (*BoolResponse, error)
	// Franchise Accounts RPC's
	CreateFranchiseAccount(context.Context, *AddFranchiseAccountRequest) (*AddResponse, error)
	GetFranchiseAccountByID(context.Context, *GetFranchiseAccountByIDRequest) (*GetFranchiseAccountByIDResponse, error)
	GetFranchiseAccounts(context.Context, *GetFranchiseAccountsRequest) (*GetFranchiseAccountsResponse, error)
	UpdateFranchiseAccountByID(context.Context, *UpdateFranchiseAccountRequest) (*UpdateResponse, error)
	DeleteFranchiseAccountByID(context.Context, *DeleteFranchiseAccountRequest) (*DeletedResponse, error)
	// Franchise Role RPC's
	CreateFranchiseRole(context.Context, *AddFranchiseRoleRequest) (*AddResponse, error)
	UpdateFranchiseRole(context.Context, *UpdateFranchiseRoleRequest) (*UpdateResponse, error)
	GetAllFranchiseRoles(context.Context, *GetByIDRequest) (*FranchiseRoleResponse, error)
	// Franchise Role Permission RPC's
	AddPermissionsToRole(context.Context, *AddRolePermission) (*AddRolePermission, error)
	UpdatePermissionsToRole(context.Context, *AddRolePermission) (*AddRolePermission, error)
	GetAllPermissionToRole(context.Context, *GetByIDRequest) (*GetAllRolePermissionDetails, error)
	mustEmbedUnimplementedAccountServiceServer()
}

// UnimplementedAccountServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountServiceServer struct{}

func (UnimplementedAccountServiceServer) CreateFranchise(context.Context, *AddFranchiseRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFranchise not implemented")
}
func (UnimplementedAccountServiceServer) UpdateFranchise(context.Context, *UpdateFranchiseRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFranchise not implemented")
}
func (UnimplementedAccountServiceServer) UpdateFranchiseStatus(context.Context, *UpdateFranchiseStatusRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFranchiseStatus not implemented")
}
func (UnimplementedAccountServiceServer) DeleteFranchise(context.Context, *DeleteFranchiseRequest) (*DeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFranchise not implemented")
}
func (UnimplementedAccountServiceServer) GetAllFranchises(context.Context, *GetFranchisesRequest) (*GetFranchisesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFranchises not implemented")
}
func (UnimplementedAccountServiceServer) GetFranchiseByID(context.Context, *GetByIDRequest) (*GetFranchiseByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFranchiseByID not implemented")
}
func (UnimplementedAccountServiceServer) GetFranchiseByBusinessName(context.Context, *GetFranchiseByName) (*GetFranchiseByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFranchiseByBusinessName not implemented")
}
func (UnimplementedAccountServiceServer) CreateFranchiseDocument(context.Context, *AddFranchiseDocumentRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFranchiseDocument not implemented")
}
func (UnimplementedAccountServiceServer) GetFranchiseDocumentByID(context.Context, *GetFranchiseDocumentRequest) (*GetFranchiseDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFranchiseDocumentByID not implemented")
}
func (UnimplementedAccountServiceServer) UpdateFranchiseDocumentByID(context.Context, *UpdateFranchiseDocumentRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFranchiseDocumentByID not implemented")
}
func (UnimplementedAccountServiceServer) DeleteFranchiseDocumentByID(context.Context, *DeleteFranchiseDocumentRequest) (*DeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFranchiseDocumentByID not implemented")
}
func (UnimplementedAccountServiceServer) CreateFranchiseAddress(context.Context, *AddFranchiseAddressRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFranchiseAddress not implemented")
}
func (UnimplementedAccountServiceServer) GetFranchiseAddressByID(context.Context, *GetFranchiseAddressRequest) (*GetFranchiseAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFranchiseAddressByID not implemented")
}
func (UnimplementedAccountServiceServer) UpdateFranchiseAddressByID(context.Context, *UpdateFranchiseAddressRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFranchiseAddressByID not implemented")
}
func (UnimplementedAccountServiceServer) CreateNewOwner(context.Context, *AddFranchiseOwnerRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNewOwner not implemented")
}
func (UnimplementedAccountServiceServer) UpdateFranchiseOwnerByID(context.Context, *UpdateFranchiseOwnerRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFranchiseOwnerByID not implemented")
}
func (UnimplementedAccountServiceServer) GetFranchiseOwnerByID(context.Context, *GetFranchiseOwnerRequest) (*GetFranchiseOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFranchiseOwnerByID not implemented")
}
func (UnimplementedAccountServiceServer) CheckIfOwnerExistsByAadharID(context.Context, *AadharNoRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckIfOwnerExistsByAadharID not implemented")
}
func (UnimplementedAccountServiceServer) CreateFranchiseAccount(context.Context, *AddFranchiseAccountRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFranchiseAccount not implemented")
}
func (UnimplementedAccountServiceServer) GetFranchiseAccountByID(context.Context, *GetFranchiseAccountByIDRequest) (*GetFranchiseAccountByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFranchiseAccountByID not implemented")
}
func (UnimplementedAccountServiceServer) GetFranchiseAccounts(context.Context, *GetFranchiseAccountsRequest) (*GetFranchiseAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFranchiseAccounts not implemented")
}
func (UnimplementedAccountServiceServer) UpdateFranchiseAccountByID(context.Context, *UpdateFranchiseAccountRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFranchiseAccountByID not implemented")
}
func (UnimplementedAccountServiceServer) DeleteFranchiseAccountByID(context.Context, *DeleteFranchiseAccountRequest) (*DeletedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFranchiseAccountByID not implemented")
}
func (UnimplementedAccountServiceServer) CreateFranchiseRole(context.Context, *AddFranchiseRoleRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFranchiseRole not implemented")
}
func (UnimplementedAccountServiceServer) UpdateFranchiseRole(context.Context, *UpdateFranchiseRoleRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFranchiseRole not implemented")
}
func (UnimplementedAccountServiceServer) GetAllFranchiseRoles(context.Context, *GetByIDRequest) (*FranchiseRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFranchiseRoles not implemented")
}
func (UnimplementedAccountServiceServer) AddPermissionsToRole(context.Context, *AddRolePermission) (*AddRolePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPermissionsToRole not implemented")
}
func (UnimplementedAccountServiceServer) UpdatePermissionsToRole(context.Context, *AddRolePermission) (*AddRolePermission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePermissionsToRole not implemented")
}
func (UnimplementedAccountServiceServer) GetAllPermissionToRole(context.Context, *GetByIDRequest) (*GetAllRolePermissionDetails, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPermissionToRole not implemented")
}
func (UnimplementedAccountServiceServer) mustEmbedUnimplementedAccountServiceServer() {}
func (UnimplementedAccountServiceServer) testEmbeddedByValue()                        {}

// UnsafeAccountServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountServiceServer will
// result in compilation errors.
type UnsafeAccountServiceServer interface {
	mustEmbedUnimplementedAccountServiceServer()
}

func RegisterAccountServiceServer(s grpc.ServiceRegistrar, srv AccountServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountService_ServiceDesc, srv)
}

func _AccountService_CreateFranchise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFranchiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateFranchise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateFranchise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateFranchise(ctx, req.(*AddFranchiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateFranchise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFranchiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateFranchise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateFranchise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateFranchise(ctx, req.(*UpdateFranchiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateFranchiseStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFranchiseStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateFranchiseStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateFranchiseStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateFranchiseStatus(ctx, req.(*UpdateFranchiseStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteFranchise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFranchiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteFranchise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteFranchise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteFranchise(ctx, req.(*DeleteFranchiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAllFranchises_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFranchisesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAllFranchises(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAllFranchises_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAllFranchises(ctx, req.(*GetFranchisesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetFranchiseByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetFranchiseByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetFranchiseByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetFranchiseByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetFranchiseByBusinessName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFranchiseByName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetFranchiseByBusinessName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetFranchiseByBusinessName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetFranchiseByBusinessName(ctx, req.(*GetFranchiseByName))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateFranchiseDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFranchiseDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateFranchiseDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateFranchiseDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateFranchiseDocument(ctx, req.(*AddFranchiseDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetFranchiseDocumentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFranchiseDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetFranchiseDocumentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetFranchiseDocumentByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetFranchiseDocumentByID(ctx, req.(*GetFranchiseDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateFranchiseDocumentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFranchiseDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateFranchiseDocumentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateFranchiseDocumentByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateFranchiseDocumentByID(ctx, req.(*UpdateFranchiseDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteFranchiseDocumentByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFranchiseDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteFranchiseDocumentByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteFranchiseDocumentByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteFranchiseDocumentByID(ctx, req.(*DeleteFranchiseDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateFranchiseAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFranchiseAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateFranchiseAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateFranchiseAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateFranchiseAddress(ctx, req.(*AddFranchiseAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetFranchiseAddressByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFranchiseAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetFranchiseAddressByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetFranchiseAddressByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetFranchiseAddressByID(ctx, req.(*GetFranchiseAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateFranchiseAddressByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFranchiseAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateFranchiseAddressByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateFranchiseAddressByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateFranchiseAddressByID(ctx, req.(*UpdateFranchiseAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateNewOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFranchiseOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateNewOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateNewOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateNewOwner(ctx, req.(*AddFranchiseOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateFranchiseOwnerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFranchiseOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateFranchiseOwnerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateFranchiseOwnerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateFranchiseOwnerByID(ctx, req.(*UpdateFranchiseOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetFranchiseOwnerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFranchiseOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetFranchiseOwnerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetFranchiseOwnerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetFranchiseOwnerByID(ctx, req.(*GetFranchiseOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CheckIfOwnerExistsByAadharID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AadharNoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CheckIfOwnerExistsByAadharID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CheckIfOwnerExistsByAadharID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CheckIfOwnerExistsByAadharID(ctx, req.(*AadharNoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateFranchiseAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFranchiseAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateFranchiseAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateFranchiseAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateFranchiseAccount(ctx, req.(*AddFranchiseAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetFranchiseAccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFranchiseAccountByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetFranchiseAccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetFranchiseAccountByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetFranchiseAccountByID(ctx, req.(*GetFranchiseAccountByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetFranchiseAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFranchiseAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetFranchiseAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetFranchiseAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetFranchiseAccounts(ctx, req.(*GetFranchiseAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateFranchiseAccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFranchiseAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateFranchiseAccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateFranchiseAccountByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateFranchiseAccountByID(ctx, req.(*UpdateFranchiseAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteFranchiseAccountByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFranchiseAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteFranchiseAccountByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_DeleteFranchiseAccountByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteFranchiseAccountByID(ctx, req.(*DeleteFranchiseAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateFranchiseRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFranchiseRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateFranchiseRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_CreateFranchiseRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateFranchiseRole(ctx, req.(*AddFranchiseRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateFranchiseRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFranchiseRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateFranchiseRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdateFranchiseRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateFranchiseRole(ctx, req.(*UpdateFranchiseRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAllFranchiseRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAllFranchiseRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAllFranchiseRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAllFranchiseRoles(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_AddPermissionsToRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRolePermission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).AddPermissionsToRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_AddPermissionsToRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).AddPermissionsToRole(ctx, req.(*AddRolePermission))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdatePermissionsToRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRolePermission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdatePermissionsToRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_UpdatePermissionsToRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdatePermissionsToRole(ctx, req.(*AddRolePermission))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAllPermissionToRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAllPermissionToRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountService_GetAllPermissionToRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAllPermissionToRole(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountService_ServiceDesc is the grpc.ServiceDesc for AccountService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFranchise",
			Handler:    _AccountService_CreateFranchise_Handler,
		},
		{
			MethodName: "UpdateFranchise",
			Handler:    _AccountService_UpdateFranchise_Handler,
		},
		{
			MethodName: "UpdateFranchiseStatus",
			Handler:    _AccountService_UpdateFranchiseStatus_Handler,
		},
		{
			MethodName: "DeleteFranchise",
			Handler:    _AccountService_DeleteFranchise_Handler,
		},
		{
			MethodName: "GetAllFranchises",
			Handler:    _AccountService_GetAllFranchises_Handler,
		},
		{
			MethodName: "GetFranchiseByID",
			Handler:    _AccountService_GetFranchiseByID_Handler,
		},
		{
			MethodName: "GetFranchiseByBusinessName",
			Handler:    _AccountService_GetFranchiseByBusinessName_Handler,
		},
		{
			MethodName: "CreateFranchiseDocument",
			Handler:    _AccountService_CreateFranchiseDocument_Handler,
		},
		{
			MethodName: "GetFranchiseDocumentByID",
			Handler:    _AccountService_GetFranchiseDocumentByID_Handler,
		},
		{
			MethodName: "UpdateFranchiseDocumentByID",
			Handler:    _AccountService_UpdateFranchiseDocumentByID_Handler,
		},
		{
			MethodName: "DeleteFranchiseDocumentByID",
			Handler:    _AccountService_DeleteFranchiseDocumentByID_Handler,
		},
		{
			MethodName: "CreateFranchiseAddress",
			Handler:    _AccountService_CreateFranchiseAddress_Handler,
		},
		{
			MethodName: "GetFranchiseAddressByID",
			Handler:    _AccountService_GetFranchiseAddressByID_Handler,
		},
		{
			MethodName: "UpdateFranchiseAddressByID",
			Handler:    _AccountService_UpdateFranchiseAddressByID_Handler,
		},
		{
			MethodName: "CreateNewOwner",
			Handler:    _AccountService_CreateNewOwner_Handler,
		},
		{
			MethodName: "UpdateFranchiseOwnerByID",
			Handler:    _AccountService_UpdateFranchiseOwnerByID_Handler,
		},
		{
			MethodName: "GetFranchiseOwnerByID",
			Handler:    _AccountService_GetFranchiseOwnerByID_Handler,
		},
		{
			MethodName: "CheckIfOwnerExistsByAadharID",
			Handler:    _AccountService_CheckIfOwnerExistsByAadharID_Handler,
		},
		{
			MethodName: "CreateFranchiseAccount",
			Handler:    _AccountService_CreateFranchiseAccount_Handler,
		},
		{
			MethodName: "GetFranchiseAccountByID",
			Handler:    _AccountService_GetFranchiseAccountByID_Handler,
		},
		{
			MethodName: "GetFranchiseAccounts",
			Handler:    _AccountService_GetFranchiseAccounts_Handler,
		},
		{
			MethodName: "UpdateFranchiseAccountByID",
			Handler:    _AccountService_UpdateFranchiseAccountByID_Handler,
		},
		{
			MethodName: "DeleteFranchiseAccountByID",
			Handler:    _AccountService_DeleteFranchiseAccountByID_Handler,
		},
		{
			MethodName: "CreateFranchiseRole",
			Handler:    _AccountService_CreateFranchiseRole_Handler,
		},
		{
			MethodName: "UpdateFranchiseRole",
			Handler:    _AccountService_UpdateFranchiseRole_Handler,
		},
		{
			MethodName: "GetAllFranchiseRoles",
			Handler:    _AccountService_GetAllFranchiseRoles_Handler,
		},
		{
			MethodName: "AddPermissionsToRole",
			Handler:    _AccountService_AddPermissionsToRole_Handler,
		},
		{
			MethodName: "UpdatePermissionsToRole",
			Handler:    _AccountService_UpdatePermissionsToRole_Handler,
		},
		{
			MethodName: "GetAllPermissionToRole",
			Handler:    _AccountService_GetAllPermissionToRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/account.proto",
}
